### ISSUE TITLE
OCP.exec_oc_cmd("describe pod podname") fails

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#113]
OCP.exec_oc_cmd("describe pod name") returns:

/home/ec2-user/venv/lib/python3.7/site-packages/kubernetes/config/kube_config.py:496: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_dict=yaml.load(f),
Traceback (most recent call last):
  File "get_ip_addrs.py", line 53, in <module>
    print(get_ip_addrs())
  File "get_ip_addrs.py", line 46, in get_ip_addrs
    OCP.exec_oc_cmd(oc_cmd)
  File "/home/ec2-user/ocs-ci/ocs/ocp.py", line 66, in exec_oc_cmd
    return munchify(yaml.safe_load(out))
  File "/home/ec2-user/venv/lib/python3.7/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/home/ec2-user/venv/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/ec2-user/venv/lib/python3.7/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "/home/ec2-user/venv/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/ec2-user/venv/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/ec2-user/venv/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/ec2-user/venv/lib/python3.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/ec2-user/venv/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/ec2-user/venv/lib/python3.7/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/ec2-user/venv/lib/python3.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/ec2-user/venv/lib/python3.7/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/home/ec2-user/venv/lib/python3.7/site-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 10, column 37:
    Annotations:        openshift.io/scc: rook-ceph

==============================================================

When I tried something invalid, I got the following:

home/ec2-user/venv/lib/python3.7/site-packages/kubernetes/config/kube_config.py:496: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_dict=yaml.load(f),
CMD error:: Error: unknown command "xxxxxxx" for "oc"
Run 'oc --help' for usage.

Traceback (most recent call last):
  File "get_ip_addrs.py", line 53, in <module>
    print(get_ip_addrs())
  File "get_ip_addrs.py", line 46, in get_ip_addrs
    OCP.exec_oc_cmd(oc_cmd)
  File "/home/ec2-user/ocs-ci/ocs/ocp.py", line 65, in exec_oc_cmd
    out = run_cmd(cmd=oc_cmd)
  File "/home/ec2-user/ocs-ci/utility/utils.py", line 654, in run_cmd
    f"Error during execution of command: {cmd}"
ocs.exceptions.CommandFailed: Error during execution of command: ['oc', '-n', 'openshift-storage', '--kubeconfig', '/tmp/ocs-ci-cluster-ec2-user-30031/auth/kubeconfig', 'xxxxxxx', 'describe', 'pod', 'rook-ceph-agent-5h67j']

==============================================================

So I tried running the valid corresponding command from the shell and it worked:

oc -n openshift-storage --kubeconfig /tmp/ocs-ci-cluster-ec2-user-30031/auth/kubeconfig describe pod rook-ceph-agent-5h67j
Name:               rook-ceph-agent-5h67j
Namespace:          openshift-storage
Priority:           0
PriorityClassName:  <none>
Node:               ip-10-0-166-194.us-east-2.compute.internal/10.0.166.194
Start Time:         Tue, 28 May 2019 22:44:03 +0000
Labels:             app=rook-ceph-agent
                    controller-revision-hash=6848b56bb
                    pod-template-generation=1
Annotations:        openshift.io/scc: rook-ceph
Status:             Running
IP:                 10.0.166.194
Controlled By:      DaemonSet/rook-ceph-agent
Containers:
  rook-ceph-agent:
    Container ID:  cri-o://ba7d0de2fd216359bd7cabc5ec2f21ef445defbca3ef90dcc6e72c4ec8388f30
    Image:         quay.io/rhceph-dev/rook
    Image ID:      quay.io/rhceph-dev/rook@sha256:ccad618bedd562354beef8a6452510e50bfa1da9c30e0360e4ce75f06a84a8d7
    Port:          <none>
    Host Port:     <none>
    Args:
      ceph
      agent
    State:          Running
      Started:      Tue, 28 May 2019 22:45:05 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      POD_NAMESPACE:                   openshift-storage (v1:metadata.namespace)
      NODE_NAME:                        (v1:spec.nodeName)
      AGENT_MOUNT_SECURITY_MODE:       Any
      ROOK_ENABLE_SELINUX_RELABELING:  true
      ROOK_ENABLE_FSGROUP:             true
    Mounts:
      /dev from dev (rw)
      /flexmnt from flexvolume (rw)
      /lib/modules from libmodules (rw)
      /sys from sys (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from rook-ceph-system-token-w9kxj (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  flexvolume:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/kubelet-plugins/volume/exec
    HostPathType:  
  dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:  
  sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:  
  libmodules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  
  rook-ceph-system-token-w9kxj:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rook-ceph-system-token-w9kxj
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:          <none>

I am wondering if the fields at the end with colons and no spaces are confusing things.

**Comment by RazTamir** [comment]
I believe this can easily fixed with adding '-o yaml' to the end of the command you executed

**Comment by wusui** [comment]
-o yaml does not seem to work.

(venv) [ec2-user@ip-172-31-47-136 utility]$ python
Python 3.7.3 (default, May 28 2019, 22:11:24)
[GCC 8.2.1 20180905 (Red Hat 8.2.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from get_ip_addrs import get_ip_addrs
>>> get_ip_addrs()
/home/ec2-user/venv/lib/python3.7/site-packages/kubernetes/config/kube_config.py:496:
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as
the default Loader is unsafe. Please read https://msg.pyyaml.org/load for
full details.
  config_dict=yaml.load(f),
CMD error:: Error: unknown shorthand flag: 'o' in -o


Usage:
  oc describe (-f FILENAME | TYPE [NAME_PREFIX | -l label] | TYPE/NAME)
[flags]

Examples:
  # Provide details about the ruby-22-centos7 image repository
  oc describe imageRepository ruby-22-centos7

  # Provide details about the ruby-sample-build build configuration
  oc describe bc ruby-sample-build

Options:
  -A, --all-namespaces=false: If present, list the requested object(s)
across all namespaces. Namespace in current context is ignored even if
specified with --namespace.
  -f, --filename=[]: Filename, directory, or URL to files containing the
resource to describe
      --include-uninitialized=false: If true, the kubectl command applies
to uninitialized objects. If explicitly set to false, this flag overrides
other flags that make the kubectl commands apply to uninitialized objects,
e.g., "--all". Objects with empty metadata.initializers are regarded as
initialized.
  -R, --recursive=false: Process the directory used in -f, --filename
recursively. Useful when you want to manage related manifests organized
within the same directory.
  -l, --selector='': Selector (label query) to filter on, supports '=',
'==', and '!='.(e.g. -l key1=value1,key2=value2)
      --show-events=true: If true, display events related to the described
object.

Use "oc options" for a list of global command-line options (applies to all
commands).


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/ocs-ci/utility/get_ip_addrs.py", line 46, in
get_ip_addrs
    output = OCP.exec_oc_cmd(oc_cmd)
  File "/home/ec2-user/ocs-ci/ocs/ocp.py", line 65, in exec_oc_cmd
    out = run_cmd(cmd=oc_cmd)
  File "/home/ec2-user/ocs-ci/utility/utils.py", line 654, in run_cmd
    f"Error during execution of command: {cmd}"
ocs.exceptions.CommandFailed: Error during execution of command: ['oc',
'-n', 'openshift-storage', '--kubeconfig',
'/tmp/ocs-ci-cluster-ec2-user-30031/auth/kubeconfig', 'describe', 'pod',
'rook-ceph-agent-5h67j', '-o', 'yaml']
>>>

**Comment by RazTamir** [comment]
Taking this issue

**Comment by RazTamir** [comment]
Hi @wusui is there anything specific that you can achieve only with describe?
describe if a very complex operation that doesn't act like all the others so I'd prefer to handle it in the future.
Also, in the REST client, this is still not implemented so wanted to understand if 'get' doesn't provide what you are looking for

**Comment by wusui** [comment]
I don't think that this PR is important as I once thought it was.  I don't
need to make this change now.  If we need to do this in the future and the
describe command is still a problem, we could always fall back on piping
raw oc command output through subprocesses as a work around.

**Comment by gklein** [comment]
Given the last [comment](https://github.com/red-hat-storage/ocs-ci/issues/113#issuecomment-497640006)  can we close this issue?
