### ISSUE TITLE
md5sum errors - IndexError: list index out of range / OSError: pytest: reading from stdin while output is captured! Consider using -s.

### ISSUE THREAD

**Issue by Neon-White** [red-hat-storage/ocs-ci#4003]
```
tests/manage/mcg/test_object_integrity.py:83: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

original_object_path = '/original/canada.jpg'
result_object_path = '/result/canada.jpg'
awscli_pod = <ocs_ci.ocs.resources.pod.Pod object at 0x7f9da18f4ac0>

    def verify_s3_object_integrity(original_object_path, result_object_path, awscli_pod):
        """
        Verifies checksum between original object and result object on an awscli pod
    
        Args:
            original_object_path (str): The Object that is uploaded to the s3 bucket
            result_object_path (str):  The Object that is downloaded from the s3 bucket
            awscli_pod (pod): A pod running the AWSCLI tools
    
        Returns:
            bool: True if checksum matches, False otherwise
    
        """
        md5sum = shlex.split(
            awscli_pod.exec_cmd_on_pod(
                command=f"md5sum {original_object_path} {result_object_path}"
            )
        )
>       if md5sum[0] == md5sum[2]:
E       IndexError: list index out of range
```

We need to add additional data to the logs in order to better know what causes the issue, and why the list isn't long enough

**Comment by MeridianExplorer** [comment]
An adjacent issue that should be solved together with this one has started to appear recently.
The following code
```
md5sum = shlex.split(
        awscli_pod.exec_cmd_on_pod(
            command=f"md5sum {original_object_path} {result_object_path}"
        )
    )
```
Leads to this error -
`OSError: pytest: reading from stdin while output is captured!  Consider using -s.`

We should:
1. Log the values of `original_object_path`, `result_object_path` and `result_object_path`
2. Make sure they're not empty before submitting them

Once we have the logs and the issue reoccurs, we can understand what is the root cause of the issue, and then fix it properly.

**Comment by MeridianExplorer** [comment]
`test_empty_file_integrity` seems to also be affected - 
```
        # Checksum is compared between original and result object
        original_md5 = awscli_pod.exec_cmd_on_pod(
            f'sh -c "cat {original_dir}/* | md5sum"'
        )
        result_md5 = awscli_pod.exec_cmd_on_pod(
            f'sh -c "cat {original_dir}/* | md5sum"'
        )
>       assert original_md5 == result_md5
E       AssertionError: assert None == 'd41d8cd98f00...98ecf8427e  -'
E         -None
E         +'d41d8cd98f00b204e9800998ecf8427e  -'
```

**Comment by MeridianExplorer** [comment]
Should be improved by #4473

**Comment by MeridianExplorer** [comment]
This does not seem to happen anymore; I'm keeping it closed, and will reopen if needed in the future.

**Comment by sagihirshfeld** [comment]
Recently seen again in https://url.corp.redhat.com/7f5649f. The root issue is still not clear, so the need to add more logging to the function remains.
