### ISSUE TITLE
typo in clusterNamespace spec in rook-ceph-block storageClass

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#78]
In `templates/ocs-deployment/storage-manifest.yaml`, we specify storage class as:

```
  clusternamespace: {{ cluster_namespace | default('openshift-storage') }}
```
This should read `clusterNamespace` instead. Otherwise the namespace selected is not
recognized and a default namespace is used instead by rook.

**Comment by mbukatov** [comment]
Fixed by https://github.com/red-hat-storage/ocs-ci/pull/79

**Comment by wusui** [comment]
Was this fix for this problem?:

level=error msg="\t* aws_vpc_endpoint.s3: Error creating VPC Endpoint: VpcEndpointLimitExceeded: The maximum number of VPC endpoints has been reached."

The reason why I am asking is that I have the most recent version (with this checkin) and I am still seeing this problem.

**Comment by keesturam** [comment]
> Was this fix for this problem?:
> 
> level=error msg="\t* aws_vpc_endpoint.s3: Error creating VPC Endpoint: VpcEndpointLimitExceeded: The maximum number of VPC endpoints has been reached."
> 
> The reason why I am asking is that I have the most recent version (with this checkin) and I am still seeing this problem.

No, VPC Endpoint Limit Exceeded is a resource limit issue we are hitting at AWS. This issue is for the typo in storageclass that ocs-ci creates.
